apiVersion: skaffold/v2beta8
kind: Config

metadata:
  name: image
  
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
      
  local:
    push: true
    useDockerCLI: true
    
  artifacts:
    - image: mlambdanet/image-api
      context: .
      docker:
        dockerfile: Dockerfile
        
profiles:
  - name: QA
    deploy:
      helm:
        releases:
          - name: api
            namespace: images
            chartPath: helm/image
            valuesFiles: [helm/image/values.yaml, helm/image/values.dev.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
              env.server: "{{.IMAGE_SERVER}}"
              env.client_id: "{{.IMAGE_ID}}"
              env.secret: "{{.IMAGE_SECRET}}"
  
  - name: PROD
    deploy:
      helm:
        releases:
          - name: api
            namespace: images
            chartPath: helm/image
            valuesFiles: [helm/image/values.yaml, helm/image/values.prod.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
              env.server: "{{.IMAGE_SERVER}}"
              env.client_id: "{{.IMAGE_ID}}"
              env.secret: "{{.IMAGE_SECRET}}"