replicaCount: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: issuer-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  hosts:
    - host: api.mitienda.co.cr
      paths:
        - path: /image
          backend:
            serviceName: api-image
            servicePort: 80
  tls:
    - secretName: api-tls
      hosts:
        - api.mitienda.co.cr

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80