replicaCount: 1

image:
  repository: mlambdanet/image-api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: image-pull-secret
    
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /image/metrics
  prometheus.io/port: "9090"

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    cert-manager.io/cluster-issuer: issuer-prod
  hosts:
    - host: api.mitienda.co.cr
      paths:
      - path: /image
        backend:
          serviceName: api-image
          servicePort: 80

resources: 
   limits:
     cpu: 200m
     memory: 250Mi
   requests:
     cpu: 200m
     memory: 250Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
