replicaCount: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: issuer-prod
  hosts:
    - host: api.mitienda.co.cr
      paths:
        - path: /image
          backend:
            serviceName: api-image
            servicePort: 80

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80